### ISSUE TITLE
Function getODTProperties() does not convert pixel to points for 'border-left' etc...

### ISSUE THREAD

**Issue by LarsGit223** [LarsGit223/dokuwiki-plugin-odt#50]
The function getODTProperties() does not convert pixel to points for the properties 'border-left', 'border-right', 'border-top' and 'border-bottom.' (but it does for 'border').

So, e.g. the keyboard plugin uses the following CSS code:

```CSS
/* --- keyboard plugin --- */

kbd {
  color: #333333;
  background-color: white;
  text-align: center;
  border-left: 1px solid #cfcfcf;
  border-top: 1px solid #cfcfcf;
  border-right: 2px solid #666666;
  border-bottom: 2px solid #666666;
  -moz-border-radius: 4px 4px 4px 4px;
  padding-left: 1px;
  padding-top: 0px;
  padding-right: 2px;
  padding-bottom: 0px;
  margin-left: 2px;
  margin-right: 2px;
  vertical-align: top;
  font-family: sans-serif;
}
```

A call like this

```PHP
    // Get CSS properties for ODT export.
    $renderer->getODTProperties ($properties, 'kbd', NULL, NULL);
```
would return the border properties unchanged e.g. ```$properties ['border-left'] == '1px solid #cfcfcf'``` instead of returning ```$properties ['border-left'] == '1pt solid #cfcfcf'```.

If these properties are used to create a border then LibreOffice will not display the border because it does not support pixel units in borders.
